#!/bin/bash
# regen-legacy-hashes.sh — Regenerate scripts/legacy-skill-hashes.txt from git history.
#
# The manifest is a sorted list of sha256 hashes covering every version of every
# `plugins/*/skills/*/SKILL.md` blob that has ever existed in this repo. The
# Codex `--cleanup` migration uses it to verify ownership of files left over
# in `~/.codex/skills/` from the old `--user` install path — without needing
# git history at install time (the curl one-liner unpacks a tarball).
#
# Run this whenever new SKILL.md content is committed (release, or post-edit).
# CI's check-installation could also enforce that the manifest is in sync.
#
# Usage:
#   scripts/regen-legacy-hashes.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFEST="$ROOT_DIR/scripts/legacy-skill-hashes.txt"
# The hook ships its own copy because Claude Code installs the plugin to a
# cache directory without the repo's scripts/. Both files are the source of
# truth, kept identical by this regen.
HOOK_MANIFEST="$ROOT_DIR/plugins/go-workflow/hooks/legacy-skill-hashes.txt"

cd "$ROOT_DIR"

if [[ ! -d .git ]]; then
    echo "error: scripts/regen-legacy-hashes.sh must be run from a git clone" >&2
    exit 1
fi

# Collect every blob OID that has ever existed at a path matching
# plugins/<plugin>/skills/<skill>/SKILL.md, then emit <sha256> <skill_name>
# pairs. The skill name is necessary to preserve per-skill ownership during
# manifest-based cleanup — a hash that originated from skill A must not be
# accepted as proof of ownership for a candidate in directory B.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

git rev-list --objects --all 2>/dev/null \
    | awk '$2 ~ /^plugins\/[^/]+\/skills\/[^/]+\/SKILL\.md$/ {print $1, $2}' \
    | while read -r blob path; do
        skill_name="$(basename "$(dirname "$path")")"
        hash="$(git cat-file blob "$blob" 2>/dev/null | sha256sum | awk '{print $1}')"
        [[ -n "$hash" ]] && echo "$hash $skill_name"
    done \
    | sort -u >"$TMP"

count="$(wc -l < "$TMP" | tr -d ' ')"

cat > "$MANIFEST" <<EOF
# legacy-skill-hashes.txt — manifest of every gopher-ai SKILL.md blob version
# this repo has ever shipped. Each non-comment line is "<sha256> <skill_name>".
# Regenerated by scripts/regen-legacy-hashes.sh.
# Used by scripts/install-codex.sh --cleanup to safely identify legacy gopher-ai
# installs in ~/.codex/skills/ when running without git history (curl one-liner).
# Both fields must match for cleanup to consider a candidate gopher-ai-owned —
# this prevents accepting a hash from skill A as proof of ownership for skill B.
# DO NOT EDIT BY HAND — re-run the regen script after committing SKILL.md changes.
#
# Total entries: $count
EOF
cat "$TMP" >> "$MANIFEST"

# Mirror to the plugin so the SessionStart hook can read it without depending
# on the repo's scripts/ directory.
mkdir -p "$(dirname "$HOOK_MANIFEST")"
cp "$MANIFEST" "$HOOK_MANIFEST"

echo "regenerated: $MANIFEST ($count unique <hash skill_name> pairs)"
echo "mirrored to: $HOOK_MANIFEST"
